# Generated by Django 4.1.4 on 2022-12-28 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qta', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('adresse', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('credit', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QtV', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EntreeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('qt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('sommeRestante', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('adresse', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('solde', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Prix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrixUnite', models.FloatField()),
                ('PrixVente', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('CodeP', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TypeProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True)),
                ('restant', models.FloatField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionStock.client')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True)),
                ('Qtp', models.IntegerField()),
                ('Prix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StocksPrix', to='gestionStock.prix')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StockProduits', to='gestionStock.produit')),
            ],
        ),
        migrations.CreateModel(
            name='SortieStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('motif', models.CharField(max_length=30)),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionStock.produit')),
            ],
        ),
        migrations.CreateModel(
            name='ReglementVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('sommeAjoute', models.FloatField()),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionStock.vente')),
            ],
        ),
        migrations.CreateModel(
            name='ReglementFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('sommeAjoute', models.FloatField()),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionStock.facture')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='prix',
            field=models.ManyToManyField(through='gestionStock.Stock', to='gestionStock.prix'),
        ),
        migrations.AddField(
            model_name='produit',
            name='typeP',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionStock.typeproduit'),
        ),
        migrations.AddConstraint(
            model_name='prix',
            constraint=models.UniqueConstraint(fields=('PrixUnite', 'PrixVente'), name='uniquePrix'),
        ),
        migrations.AddField(
            model_name='facture',
            name='fournisseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionStock.fournisseur'),
        ),
        migrations.AddField(
            model_name='entreestock',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionStock.produit'),
        ),
        migrations.AddField(
            model_name='composer',
            name='prix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionStock.prix'),
        ),
        migrations.AddField(
            model_name='composer',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionStock.produit'),
        ),
        migrations.AddField(
            model_name='composer',
            name='vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionStock.vente'),
        ),
        migrations.AddField(
            model_name='avoir',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionStock.facture'),
        ),
        migrations.AddField(
            model_name='avoir',
            name='prix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionStock.prix'),
        ),
        migrations.AddField(
            model_name='avoir',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionStock.produit'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('Prix', 'produit'), name='uniqueStock'),
        ),
    ]
