# Generated by Django 4.1.4 on 2022-12-27 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrixUnite', models.FloatField()),
                ('PrixVente', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('CodeP', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True)),
                ('Qtp', models.IntegerField()),
                ('PrixUnite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StocksPrixU', to='gestionStock.prix')),
                ('PrixVente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StocksPrixV', to='gestionStock.prix')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StockProduits', to='gestionStock.produit')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='prix',
            field=models.ManyToManyField(through='gestionStock.Stock', to='gestionStock.prix'),
        ),
        migrations.AddConstraint(
            model_name='prix',
            constraint=models.UniqueConstraint(fields=('PrixUnite', 'PrixVente'), name='uniquePrix'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('PrixUnite', 'PrixVente', 'produit'), name='uniqueStock'),
        ),
    ]
