# Generated by Django 4.1.4 on 2022-12-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='sommeRestante',
            field=models.FloatField(default=0),
        ),
    ]
