# Generated by Django 4.1.4 on 2022-12-30 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0002_alter_facture_sommerestante'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='prix',
            name='uniquePrix',
        ),
    ]
