# Generated by Django 4.1.4 on 2023-01-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0003_remove_prix_uniqueprix'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='remise',
            field=models.FloatField(default=0),
        ),
    ]
