# Generated by Django 4.1.4 on 2022-12-28 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0004_vente_client_alter_client_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='restant',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ReglementVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('sommeAjoute', models.FloatField()),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionStock.vente')),
            ],
        ),
    ]
