# Generated by Django 4.1.4 on 2023-01-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0004_facture_remise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglementfacture',
            name='sommeAjoute',
            field=models.FloatField(default=0),
        ),
    ]
