# Generated by Django 4.1.4 on 2023-01-01 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0005_alter_reglementfacture_sommeajoute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglementfacture',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reglementfacture',
            name='facture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionStock.facture'),
        ),
    ]
