# Generated by Django 4.1.4 on 2022-12-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0006_facture_fournisseur_typeproduit_sortiestock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facture',
            old_name='sommePaye',
            new_name='sommeRestante',
        ),
    ]
