# Generated by Django 4.1.4 on 2023-01-06 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0006_alter_reglementfacture_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Prix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StocksPrix', to='gestionStock.prix'),
        ),
    ]
