# Generated by Django 4.1.4 on 2023-01-06 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0006_alter_reglementfacture_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglementvente',
            name='sommeAjoute',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='reglementvente',
            name='vente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionStock.vente'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Prix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StocksPrix', to='gestionStock.prix'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='restant',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
