# Generated by Django 4.1.4 on 2023-01-07 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0007_alter_stock_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sortiestock',
            name='produit',
        ),
        migrations.AddField(
            model_name='sortiestock',
            name='qt',
            field=models.IntegerField(default=0, verbose_name='quantité déstocké'),
        ),
        migrations.AddField(
            model_name='sortiestock',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionStock.stock'),
        ),
    ]
