# Generated by Django 4.1.4 on 2023-01-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0007_alter_reglementvente_sommeajoute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglementvente',
            name='date',
            field=models.DateField(),
        ),
    ]
