# Generated by Django 4.1.4 on 2023-01-13 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0008_remove_sortiestock_produit_sortiestock_qt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
