# Generated by Django 4.1.4 on 2023-01-24 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionStock', '0009_alter_vente_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionStock.fournisseur'),
        ),
        migrations.AlterField(
            model_name='reglementfacture',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionStock.facture'),
        ),
        migrations.AlterField(
            model_name='reglementvente',
            name='vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionStock.vente'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionStock.client'),
        ),
    ]
